[tool.mypy]
python_version = "3.13"
check_untyped_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
warn_return_any = true
warn_unused_ignores = true
exclude = "sst\\.pyi"

[tool.ruff]
line-length = 88
target-version = "py313"
lint.select = ["E", "F", "I", "B", "UP"]
exclude = ["__pycache__", "venv", ".venv", "build", "dist", "sst.pyi"]
