# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str

    class ProspectBucket:
        name: str
        type: str

    class ProspectVisionary:
        service: str
        type: str
        url: str

    class ProspectVpc:
        bastion: str
        type: str

    class ProspectWeb:
        type: str
        url: str
