repos:
  # Lint-staged (JS/TS)
  - repo: local
    hooks:
      - id: lint-staged
        name: Lint staged JS/TS files
        entry: pnpm --filter web lint-staged
        language: system
        pass_filenames: false
        files: ^apps/web/

  # Black (Python formatter)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: Format with Black
        language_version: python3
        files: ^apps/visionary/

  # Mypy (Python type checker)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        name: Type check with mypy
        language_version: python3
        files: ^apps/visionary/

  # Ruff (Python linter)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        name: Lint with Ruff
        language_version: python3
        files: ^apps/visionary/
