repos:
  # Lint-staged (ESLint / Prettier / Typescript)
  - repo: local
    hooks:
      - id: lint-staged
        name: Lint staged JS/TS files
        entry: pnpm --filter web lint-staged
        language: system
        pass_filenames: false
        files: ^app/

  # Mypy (Python type checker)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        name: Type check with mypy
        language_version: python3
        files: ^visionary/

  # Ruff (Python linter / formatter)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        name: Lint with Ruff
        language_version: python3
        files: ^visionary/
