[tool.black]
line-length = 88
target-version = ["py313"]

[tool.mypy]
python_version = "3.13"
check_untyped_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
warn_return_any = true
warn_unused_ignores = true

[tool.ruff]
line-length = 88
lint.select = ["E", "F", "I", "B", "UP"]
exclude = ["__pycache__", "venv", ".venv", "build", "dist"]

[tool.pixi.workspace]
authors = ["Chris Carrick <chris@crcarrick.dev>"]
channels = ["conda-forge"]
name = "visionary"
platforms = ["osx-arm64", "osx-64", "linux-64"]
version = "0.1.0"

[tool.pixi.tasks]
dev = "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
typecheck = "mypy ."
lint = "ruff check ."
format = "black . && ruff check . --fix"
fix = "ruff check . --fix && black ."

[tool.pixi.dependencies]
python = "3.13.*"
fastapi = ">=0.115.12,<0.116"
uvicorn = ">=0.34.1,<0.35"
opencv = ">=4.11.0,<5"
moviepy = ">=1.0.3,<2"
ruff = ">=0.11.6,<0.12"
black = ">=25.1.0,<26"
mypy = ">=1.15.0,<2"
ffmpeg = ">=7.1.1,<8"
